const { google } = require("googleapis");
const path = require("path");
const fs = require("fs");

let androidpublisherClient = null;

/**
 * Initializes and caches the Google Play Developer API (androidpublisher:v3) client
 */
function getPublisherClient() {
  if (androidpublisherClient) return androidpublisherClient;

  const keyPath = process.env.GOOGLE_PLAY_KEY_PATH
    ? path.resolve(process.cwd(), process.env.GOOGLE_PLAY_KEY_PATH)
    : path.join(__dirname, "../config/google-play-service-account.json");

  if (!fs.existsSync(keyPath)) {
    throw new Error(`Google Play Service Account key file not found at: ${keyPath}`);
  }

  const auth = new google.auth.GoogleAuth({
    keyFile: keyPath,
    scopes: ["https://www.googleapis.com/auth/androidpublisher"],
  });

  androidpublisherClient = google.androidpublisher({
    version: "v3",
    auth,
  });

  console.log("[GooglePlayService] Google Play Android Publisher v3 initialized successfully");
  return androidpublisherClient;
}

/**
 * Verifies a one-time in-app product purchase with Google Play Developer API
 * 
 * @param {Object} params
 * @param {string} [params.packageName] - Android application package name (e.g. com.babylens)
 * @param {string} params.productId - Product SKU (e.g. babylens_photoshoot_1)
 * @param {string} params.purchaseToken - Purchase token generated by Google Play on the device
 * @returns {Promise<Object>} Verified purchase details from Google
 */
async function verifyProductPurchase({ packageName, productId, purchaseToken }) {
  const client = getPublisherClient();
  const pkg = packageName || process.env.GOOGLE_PLAY_PACKAGE_NAME || "com.babylens";

  console.log(`[GooglePlayService] Verifying purchase with Google: pkg=${pkg}, product=${productId}`);

  try {
    const res = await client.purchases.products.get({
      packageName: pkg,
      productId,
      token: purchaseToken,
    });

    const purchase = res.data;
    console.log(`[GooglePlayService] Google verification response for ${productId}: purchaseState=${purchase.purchaseState}, orderId=${purchase.orderId}`);

    // Google Play purchaseState enum:
    // 0 = Purchased
    // 1 = Canceled
    // 2 = Pending
    if (purchase.purchaseState !== 0) {
      const stateMap = {
        1: "Purchase was canceled or refunded",
        2: "Purchase payment is still pending approval",
      };
      const message = stateMap[purchase.purchaseState] || `Invalid purchase state: ${purchase.purchaseState}`;
      const error = new Error(message);
      error.status = 400;
      error.code = "INVALID_PURCHASE_STATE";
      error.details = purchase;
      throw error;
    }

    return {
      isValid: true,
      orderId: purchase.orderId,
      purchaseTimeMillis: purchase.purchaseTimeMillis,
      purchaseState: purchase.purchaseState,
      consumptionState: purchase.consumptionState,
      developerPayload: purchase.developerPayload,
      acknowledgementState: purchase.acknowledgementState,
      raw: purchase,
    };
  } catch (err) {
    console.error(`[GooglePlayService] Verification failed for product ${productId}:`, err.message);
    if (err.code === "INVALID_PURCHASE_STATE") throw err;

    const error = new Error(`Google Play verification failed: ${err.message}`);
    error.status = err.status || 400;
    error.code = "GOOGLE_PLAY_VERIFICATION_FAILED";
    error.originalError = err;
    throw error;
  }
}

/**
 * Acknowledges an in-app product purchase with Google Play
 * Required within 3 days of purchase if not consumed immediately
 */
async function acknowledgePurchase({ packageName, productId, purchaseToken, developerPayload }) {
  const client = getPublisherClient();
  const pkg = packageName || process.env.GOOGLE_PLAY_PACKAGE_NAME || "com.babylens";

  try {
    await client.purchases.products.acknowledge({
      packageName: pkg,
      productId,
      token: purchaseToken,
      requestBody: {
        developerPayload,
      },
    });
    console.log(`[GooglePlayService] Purchase acknowledged successfully for ${productId}`);
    return true;
  } catch (err) {
    console.warn(`[GooglePlayService] Acknowledge purchase warning: ${err.message}`);
    return false;
  }
}

module.exports = {
  getPublisherClient,
  verifyProductPurchase,
  acknowledgePurchase,
};
